services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app # Syncs code for hot-reload
      - ./backend/db.sqlite3:/app/db.sqlite3 # Persists DB
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
